services:
  app:
    build: .
    links:
      - db
    ports:
      - "3000:3000"
  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=onlinebookstore

    volumes:
      - ./setup:/docker-entrypoint-initdb.d/:ro